import Head from 'next/head';
import { format, parseISO, add } from 'date-fns';

import { blogPosts } from '../../lib/data';

export default function BlogPage({ title, date, content }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className="border-b border-gray-200 mb-2">
          <h2 className="text-2xl font-bold">{title}</h2>
          <small className="text-gray-600">
            {format(parseISO(date), 'MMMM do, uuu')}
          </small>
        </header>
        <div className="">{content}</div>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  console.log(context);
  const { params } = context;
  return {
    props: blogPosts.find((item) => item.slug === params.slug),
  };
}

export async function getStaticPaths() {
  return {
    paths: blogPosts.map((item) => ({
      params: {
        slug: item.slug,
      },
    })),
    fallback: false,
  };
}
