import Head from 'next/head';
import Link from 'next/link';
import { format, parseISO, add } from 'date-fns';

import { blogPosts } from '../lib/data';

export default function Home() {
  return (
    <div>
      <Head>
        <title>BLOGO |</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-4 ">
        {blogPosts.map((item) => (
          <BlogListItem key={item.slug} {...item} />
        ))}
      </div>
    </div>
  );
}

function BlogListItem({ slug, title, date, content }) {
  return (
    <Link href={`/blog/${slug}`} passHref>
      <div className="border border-gray-400 shadow hover:shadow-md hover:border-gray-700 rounded-md p-4 transition duration-300 ease-in-out cursor-pointer">
        <div>
          <a className=" font-bold ">{title}</a>
        </div>
        <small className="text-gray-600">
          {format(parseISO(date), 'MMMM do, uuu')}
        </small>
        <div>{content}</div>
      </div>
    </Link>
  );
}
